###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off

file_map = {
    
    "test.baml": "generator target {\n    // Valid values: \"python/pydantic\", \"typescript\", \"ruby/sorbet\"\n    output_type \"python/pydantic\"\n    \n    // Where the generated code will be saved (relative to baml_src/)\n    output_dir \"../\"\n    \n    // What interface you prefer to use for the generated code (sync/async)\n    // Both are generated regardless of the choice, just modifies what is exported\n    // at the top level\n    default_client_mode \"sync\"\n    \n    // Version of runtime to generate code for (should match installed baml-py version)\n    version \"0.67.0\"\n}\n\nclient<llm> GPT4o {\n  provider openai\n  options {\n    model gpt-4o\n    api_key env.OPENAI_API_KEY\n  }\n} \n\nclass Resume {\n  name string\n  education Education[] @description(\"Extract in the same order listed\")\n  skills string[] @description(\"Only include programming languages\")\n}\n\nclass Education {\n  school string\n  degree string\n  year int\n}\n\nfunction ExtractResume(resume_text: string) -> Resume {\n  // see clients.baml\n  client GPT4o\n\n  // The prompt uses Jinja syntax. Change the models or this text and watch the prompt preview change!\n  prompt #\"\n    Parse the following resume and return a structured representation of the data in the schema below.\n\n    Resume:\n    ---\n    {{ resume_text }}\n    ---\n\n    {# special macro to print the output instructions. #}\n    {{ ctx.output_format }}\n  \"#\n}\n\ntest Test1 {\n  functions [ExtractResume]\n  args {\n    resume_text #\"\n      John Doe\n\n      Education\n      - University of California, Berkeley\n        - B.S. in Computer Science\n        - 2020\n\n      Skills\n      - Python\n      - Java\n      - C++\n    \"#\n  }\n}",
}

def get_baml_files():
    return file_map